### ISSUE TITLE
download_revisitop1m(self) to download_revisitop1m(self, DATA_PATH)

### ISSUE THREAD

**Issue by nobobobo** [cvg/glue-factory#1]
Hi, when I tried to run the training command mentioned [here](https://github.com/cvg/glue-factory/tree/main#:~:text=python%20%2Dm%20gluefactory.train%20sp%2Blg_homography%20%5C%20%20%23%20experiment%20name%0A%20%20%20%20%2D%2Dconf%20gluefactory/configs/superpoint%2Dopen%2Blightglue_homography.yaml), it returns the following error. It seems the method `HomographyDataset.download_revisitop1m()` should be revised as `def download_revisitop1m(self, DATA_PATH)`

sh-4.2$ python -m gluefactory.train sp+lg_homography --conf gluefactory/configs/superpoint-open+lightglue_homography.yaml
[10/05/2023 17:33:43 gluefactory INFO] Starting experiment sp+lg_homography
[10/05/2023 17:33:45 gluefactory INFO] Using device cuda
[10/05/2023 17:33:47 gluefactory.datasets.base_dataset INFO] Creating dataset HomographyDataset
/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/data/revisitop1m
[10/05/2023 17:33:47 gluefactory.datasets.homographies INFO] Downloading the revisitop1m dataset.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/train.py", line 685, in <module>
    main_worker(0, conf, output_dir, args)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/train.py", line 622, in main_worker
    training(rank, conf, output_dir, args)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/train.py", line 237, in training
    dataset = get_dataset(data_conf.name)(data_conf)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/datasets/base_dataset.py", line 142, in __init__
    self._init(self.conf)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/datasets/homographies.py", line 93, in _init
    self.download_revisitop1m(data_dir)
TypeError: HomographyDataset.download_revisitop1m() takes 1 positional argument but 2 were given

**Comment by sarlinpe** [comment]
Thanks for reporting this, fixed.
