### ISSUE TITLE
ModuleNotFoundError: No module named 'homography_est'

### ISSUE THREAD

**Issue by 2805651606** [cvg/glue-factory#107]
python -m gluefactory.eval.hpatches --conf gluefactory/configs/superpoint+lsd+gluestick.yaml --overwrite
报下面的错误
[09/13/2024 11:16:10 gluefactory.datasets.base_dataset INFO] Creating dataset HPatches
  0%|                                                                                                                                                                  | 0/540 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/loftr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/mambaforge/envs/loftr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/eval/hpatches.py", line 207, in <module>
    s, f, r = pipeline.run(
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/eval/eval_pipeline.py", line 89, in run
    s, f, r = self.run_eval(self.get_dataloader(), pred_file)
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/eval/hpatches.py", line 132, in run_eval
    pose_results_i = eval_homography_robust(
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/eval/utils.py", line 137, in eval_homography_robust
    estimator = load_estimator("homography", conf["estimator"])(conf)
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/robust_estimators/__init__.py", line 8, in load_estimator
    module = __import__(module_path, fromlist=[""])
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/WSX/glue-factory/gluefactory/robust_estimators/homography/homography_est.py", line 3, in <module>
    from homography_est import (
ModuleNotFoundError: No module named 'homography_est'

**Comment by rpautrat** [comment]
Hi, did you install the extra dependencies, as suggested in the README? This is necessary to use homography_est:
```
python3 -m pip install -e .[extra]
```
