### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'last_print_t'

### ISSUE THREAD

**Issue by I-am-PixelPioneer** [cvg/glue-factory#108]
Hi,thank you for your nice work.But I encountered the following problems while training lightglue and superpoint.The following is the complete log.

D:\anaconda\envs\pytorch\python.exe C:\Users\aaa\Desktop\glue-factory-main\gluefactory\train.py sp+lg_homography "\\" --conf configs/superpoint+lightglue_homography.yaml "\\" data.batch_size=32 
[09/20/2024 16:31:33 gluefactory INFO] Starting experiment sp+lg_homography
Traceback (most recent call last):
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\train.py", line 691, in <module>
    main_worker(0, conf, output_dir, args)
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\train.py", line 628, in main_worker
    training(rank, conf, output_dir, args)
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\train.py", line 258, in training
    dataset = get_dataset(data_conf.name)(data_conf)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\datasets\base_dataset.py", line 143, in __init__
    self._init(self.conf)
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\datasets\homographies.py", line 92, in _init
    self.download_revisitop1m()
  File "C:\Users\aaa\Desktop\glue-factory-main\gluefactory\datasets\homographies.py", line 140, in download_revisitop1m
    torch.hub.download_url_to_file(url_base + list_name, tmp_dir / list_name)
  File "D:\anaconda\envs\pytorch\Lib\site-packages\torch\hub.py", line 648, in download_url_to_file
    with tqdm(total=file_size, disable=not progress,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1098, in __init__
    self.refresh(lock_args=self.lock_args)
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1347, in refresh
    self.display()
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1495, in display
    self.sp(self.__str__() if msg is None else msg)
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 459, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 452, in fp_write
    fp.write(str(s))
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\utils.py", line 196, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
Exception ignored in: <function tqdm.__del__ at 0x0000024C8C4D9760>
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1148, in __del__
    self.close()
  File "D:\anaconda\envs\pytorch\Lib\site-packages\tqdm\std.py", line 1277, in close
    if self.last_print_t < self.start_t + self.delay:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'tqdm' object has no attribute 'last_print_t'

进程已结束，退出代码为 1

**Comment by JDBSK** [comment]
do you have solved this problem yet? I also meet this problem
