### ISSUE TITLE
Feature Extraction before LightGlue training on MegaDepth failed with "Missing key {'depth_keypoints', 'valid_depth_keypoints'}"

### ISSUE THREAD

**Issue by nobobobo** [cvg/glue-factory#12]
Hi, while I am going through the document and trying to pre-extract features on MegaDepth, I face the following error: 

sh-4.2$ python -m gluefactory.scripts.export_megadepth --method sp_open --num_workers 8
0 / 193 0275
[10/10/2023 14:13:42 gluefactory.datasets.base_dataset INFO] Creating dataset MegaDepth
[10/10/2023 14:13:42 gluefactory.datasets.megadepth INFO] Sampling new train data with seed 0.
  0%|                                                                                                 | 0/314 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/scripts/export_megadepth.py", line 178, in <module>
    run_export(feature_file, scene, args)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/scripts/export_megadepth.py", line 145, in run_export
    export_predictions(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec2-user/SageMaker/image_stitching/dev/glue-factory/gluefactory/utils/export_predictions.py", line 38, in export_predictions
    raise ValueError(f"Missing key {set(keys) - set(pred.keys())}")
ValueError: Missing key {'depth_keypoints', 'valid_depth_keypoints'}

I checked that SuperPoint's prediction of MegaDepth data does not contain those keys, instead only having ["keypoints", "descriptors", "keypoint_scores"].

**Comment by Phil26AT** [comment]
Hi @nobobobo

This is an artifact of an experimental feature where we export sparse depth per keypoint. I pushed a fix to PR #13. Please let us know if this fixes your issue.
