### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by liutao14** [cvg/glue-factory#28]

**Comment by D-S-Kolesnikova** [comment]
Hello, could you please help me. I meet **attributeError: 'tqdm' object has no attribute 'last_print_t"** such error when starting training by script:
`python -m gluefactory.train sp+lg_homography --conf gluefactory/configs/superpoint+lightglue_homography.yaml `

full log:
[10/25/2023 14:29:55 gluefactory INFO] Starting experiment sp+lg_homography                                                                   [10/25/2023 14:29:55 gluefactory INFO] Using device cpu  --- Logging error ---                                                                                                                         [10/25/2023 14:30:00 gluefactory.datasets.base_dataset INFO] Creating dataset HomographyDataset  --- Logging error ---                                                                                                                         [10/25/2023 14:30:00 gluefactory.datasets.homographies INFO] Downloading the revisitop1m dataset. --- Logging error ---                                                                                                                         Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "D:\glue-factory\gluefactory\train.py", line 691, in <module>
              main_worker(0, conf, output_dir, args) 
File "D:\glue-factory\gluefactory\train.py", line 628, in main_worker 
               training(rank, conf, output_dir, args) 
File "D:\glue-factory\gluefactory\train.py", line 258, in training
              dataset = get_dataset(data_conf.name)(data_conf)                                                                                                        
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "D:\glue-factory\gluefactory\datasets\base_dataset.py", line 143, in __init__                                                             
             self._init(self.conf)
File "D:\glue-factory\gluefactory\datasets\homographies.py", line 92, in _init
             self.download_revisitop1m()
File "D:\glue-factory\gluefactory\datasets\homographies.py", line 140, in download_revisitop1m 
             torch.hub.download_url_to_file(url_base + list_name, tmp_dir / list_name)
File "D:\glue-factory\trainingEnv\Lib\site-packages\torch\hub.py", line 648, in download_url_to_file                                            
            with tqdm(total=file_size, disable=not progress,  
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\glue-factory\trainingEnv\Lib\site-packages\tqdm\std.py", line 1097, in __init__
            self.sp = self.status_printer(self.fp)                                                                                                                  
            ^^^^^^^^^^^^^^^^^^^^^^
File "D:\glue-factory\trainingEnv\Lib\site-packages\tqdm\std.py", line 451, in status_printer                                                   
            getattr(sys.stderr, 'flush', lambda: None)()
OSError: [WinError 1] Incorrect function 
Exception ignored in: <function tqdm.__del__ at 0x0000017962825BC0>                                                                           Traceback (most recent call last):
File "D:\glue-factory\trainingEnv\Lib\site-packages\tqdm\std.py", line 1149, in __del__                                                         
            self.close()
File "D:\glue-factory\trainingEnv\Lib\site-packages\tqdm\std.py", line 1278, in close
            if self.last_print_t < self.start_t + self.delay:
**AttributeError: 'tqdm' object has no attribute 'last_print_t'**

**Comment by MrPolo-AI** [comment]
I have the same issue:
AttributeError: 'tqdm' object has no attribute 'last_print_t'

Did you figure out why? Thanks.
