### ISSUE TITLE
No module named 'resource'

### ISSUE THREAD

**Issue by UyCode** [cvg/glue-factory#4]
when I run the command `python -m gluefactory.eval.hpatches --conf superpoint+lightglue-official --overwrite eval.estimator=poselib eval.ransac_th=-1` after installing all dependencies, I got the error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\glue-factory\gluefactory\eval\hpatches.py", line 6, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

**Comment by UyCode** [comment]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "E:\glue-factory\gluefactory\__init__.py", line 2, in <module>
    from .utils.experiments import load_experiment  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\glue-factory\gluefactory\utils\experiments.py", line 11, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
``` 
But I already have install all the dependencies and can find it manually

**Comment by rpautrat** [comment]
Hi, did you try manually reinstalling the latest version of these two libraries?
```
pip install --upgrade resource omegaconf
```

**Comment by sarlinpe** [comment]
The original issue is fixed by https://github.com/cvg/glue-factory/commit/1709021473f9290922a150435b565b2971cf8c42.
